"""
Internal models used by the vector repository.
"""

from typing import Any
from pydantic import BaseModel, Field, model_validator


class DenseVector(BaseModel):
    """
    Dense embedding generated by an embedding model.
    """

    values: list[float]


class SparseVector(BaseModel):
    """
    Sparse embedding used for keyword-based retrieval.
    """

    indices: list[int]
    values: list[float]

    @model_validator(mode="after")
    def validate_lengths(self) -> "SparseVector":
        if len(self.indices) != len(self.values):
            raise ValueError(
                "indices and values must have the same length."
            )
        return self


class VectorDocument(BaseModel):
    """
    Vector document ready to be stored in the vector database.
    """

    id: str

    dense_vector: DenseVector | None = None

    sparse_vector: SparseVector | None = None

    metadata: dict[str, Any] = Field(default_factory=dict)

    @model_validator(mode="after")
    def validate_vectors(self) -> "VectorDocument":
        if self.dense_vector is None and self.sparse_vector is None:
            raise ValueError(
                "Either dense_vector or sparse_vector must be provided."
            )
        return self


class QueryVector(BaseModel):
    dense_vector: DenseVector | None = None
    sparse_vector: SparseVector | None = None

class QueryResult(BaseModel):
    id: str

    score: float
    text: str

    metadata: dict[str, Any] = Field(default_factory=dict)

    dense_vector: DenseVector | None = None

    sparse_vector: SparseVector | None = None

class UpsertResponse(BaseModel):
    upserted_count: int

class DeleteResponse(BaseModel):
    deleted: bool