version: "3.9"

services:
  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    # environment:
    #   - DATABASE_URL=postgresql://user:pass@db:5432/mydb

  db:
    image: postgres:15
    restart: always
    env_file:
      - .env
    # environment:
    #   POSTGRES_DB: mydb
    #   POSTGRES_USER: user
    #   POSTGRES_PASSWORD: pass
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
