from datetime import datetime

from langchain_core.tools import tool


@tool
def document_metadata() -> str:
    """
    Returns metadata to include in generated documents.
    """

    return (
        f"Generated On: {datetime.now():%d-%m-%Y %H:%M}\n"
        "Generated By: Autonomous AI Agent"
    )